# Generated by Django 4.2.30 on 2026-09-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotpverifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserOTPIDVerifications',
        ),
        migrations.DeleteModel(
            name='UserOTPVerifications',
        ),
    ]
