# Generated by Django 4.2.30 on 2026-10-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_repair_missing_news_table'),
        ('magazin', '0003_repair_missing_news_table'),
    ]

    operations = [
    ]
