# Generated by Django 4.2.30 on 2026-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_cart_promo_code_id_alter_cart_user_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
